[workspace]
authors = ["Al Graham <llansteffan@hotmail.com>"]
channels = ["conda-forge"]
name = "documentation"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
mkdocs = ">=1.6.1,<2"
mkdocs-jupyter = ">=0.25.1,<0.26"
mkdocs-material = ">=9.7.1,<10"
click = "==8.2.1"
